StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{67297343061640F9}" {
   Id "ABF-AmmoType_M714"
   Target_en_us "Smoke Round - White"
   Modified 1730772076
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6712E846F97276FF}" {
   Id "ABF-Crate_Close"
   Target_en_us "Close"
   Target_de_de "Schließen"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6712E846E75BE994}" {
   Id "ABF-Crate_Open"
   Target_en_us "Open"
   Target_de_de "Öffnen"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E82C}" {
   Id "ABF-EditableEntity_ArsenalBox_101_Name"
   Target_en_us "101st Arsenal"
   Target_de_de "101st Arsenal"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A92AF54EEA}" {
   Id "ABF-EditableEntity_SupplyBox_Accesories_Name"
   Target_en_us "Accessories Supply Box"
   Target_de_de "Zubehör Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AE7309AF30}" {
   Id "ABF-EditableEntity_SupplyBox_Accessories_Description"
   Target_en_us "Supply box filled with accessories for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Zubehör für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6712E84D6B173F3D}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_556_Belt_Description"
   Target_en_us "Supply box filled with 5.56mm belt ammunition for the 101st"
   Target_de_de "Versorgungsbox gefüllt 5.56mm Gurt Munition mit für die 101st"
   Modified 1729674851
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6712E84D6E62CE86}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_556_Belt_Name"
   Target_en_us "5.56mm Belts Supply Box"
   Target_de_de "5.56mm Gurt Munition Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D5925C8665}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_556_Description"
   Target_en_us "Supply box filled with 5.56mm ammunition for the 101st"
   Target_de_de "Versorgungsbox gefüllt 5.56mm Munition mit für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D42B09F9AA}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_556_Name"
   Target_en_us "5.56mm Ammunition Supply Box"
   Target_de_de "5.56mm Munition Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A9A239C3AC}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_762_Belt_Description"
   Target_en_us "Supply box filled with 7.62mm belt ammunition for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit 7.62mm Munition für die 101st"
   Modified 1729674825
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A9A639D6AB}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_762_Belt_Name"
   Target_en_us "7.62mm Belt Ammunition Supply Box"
   Target_de_de "7.62mm Munition Versorgungsbox"
   Modified 1729674831
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AE69DF15B8}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_AT_Description"
   Target_en_us "Supply box filled with AT ammunition for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Panzerabwehrmunition für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A9249D33A8}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_AT_Name"
   Target_en_us "AT Ammunition Supply Box"
   Target_de_de "Panzerabwehrmunition Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D235489345}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_Launchers_Description"
   Target_en_us "Supply box filled with launchers for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Raketenwerfer für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D238897B80}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_Launchers_Name"
   Target_en_us "Launcher Supply Box"
   Target_de_de "Raketenwerfer Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AE9D349F4D}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_Mortar_Description"
   Target_en_us "Supply box filled with mortar ammunition for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Mörsermunition für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A939C1916A}" {
   Id "ABF-EditableEntity_SupplyBox_Ammo_Mortar_Name"
   Target_en_us "Mortar Ammunition Supply Box"
   Target_de_de "Mörsermunition Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AE6293381F}" {
   Id "ABF-EditableEntity_SupplyBox_Equipment_Description"
   Target_en_us "Supply box filled with equipment for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Ausrüstung für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A932EFD1A9}" {
   Id "ABF-EditableEntity_SupplyBox_Equipment_Name"
   Target_en_us "Equipment Supply Box"
   Target_de_de "Ausrüstungs Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AE8CC7F3D9}" {
   Id "ABF-EditableEntity_SupplyBox_Explosives_Description"
   Target_en_us "Supply box filled with Explosives for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Sprengstoffe für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D26950FAA4}" {
   Id "ABF-EditableEntity_SupplyBox_Explosives_Grenades_Description"
   Target_en_us "Supply box filled with grenades for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit Granatenfür die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D298ED9DAE}" {
   Id "ABF-EditableEntity_SupplyBox_Explosives_Grenades_Name"
   Target_en_us "Grenades Supply Box"
   Target_de_de "Granaten Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6718B31DF48C773A}" {
   Id "ABF-EditableEntity_SupplyBox_Explosives_Grenades_UGL_Description"
   Target_en_us "Supply box filled with 40 mm underbarrel grenade launcher ammunition for the 101st"
   Modified 1729675313
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6718B31DC03BB089}" {
   Id "ABF-EditableEntity_SupplyBox_Explosives_Grenades_UGL_Name"
   Target_en_us "40mm UGL Grenades Supply Box"
   Modified 1729675343
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948A90F44FA75}" {
   Id "ABF-EditableEntity_SupplyBox_Explosives_Name"
   Target_en_us "Explosives Supply Box"
   Target_de_de "Sprengstoffe Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D3E15DE598}" {
   Id "ABF-EditableEntity_SupplyBox_Medical_Description"
   Target_en_us "Supply box filled with medical equipment for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit medizinischer Ausrüstung für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AEFDE73938}" {
   Id "ABF-EditableEntity_SupplyBox_Medical_Infusions_Description"
   Target_en_us "Supply box filled with 7.62mm ammunition for the 101st"
   Target_de_de "Versorgungsbox gefüllt mit 7.62mm Munition für die 101st"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{66E948AEE43FC045}" {
   Id "ABF-EditableEntity_SupplyBox_Medical_Infusions_Name"
   Target_en_us "Medical Infusions Supply Box"
   Target_de_de "Medizinische Infusionen Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FAB5D21E339A56}" {
   Id "ABF-EditableEntity_SupplyBox_Medical_Name"
   Target_en_us "Medical Supply Box"
   Target_de_de "Medizinische Versorgungsbox"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E96B}" {
   Id "ABF-Faction-101"
   Target_en_us "101st Airborne"
   Target_de_de "101st Airborne"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E979}" {
   Id "ABF-Faction-101-UC"
   Target_en_us "101ST AIRBORNE"
   Target_de_de "101ST AIRBORNE"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{67297344BA251748}" {
   Id "ABF-Magazine_M714_Description"
   Target_en_us "White smoke grenade for an M203 grenade launcher."
   Modified 1730809307
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{67297344B403CA71}" {
   Id "ABF-Magazine_M714_Name"
   Target_en_us "M714 - White Smoke Round"
   Modified 1730772305
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6724CB1A2E3D58BA}" {
   Id "ABF-Map-Close"
   Target_en_us "Close Map"
   Modified 1730472322
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{671EBC86FDFBEEC2}" {
   Id "ABF-Map-Fold"
   Target_en_us "Fold Map"
   Modified 1730472330
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{671EBC86F2FFB090}" {
   Id "ABF-Map-Open"
   Target_en_us "Open Map"
   Modified 1730472337
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{671EBC86C471CE86}" {
   Id "ABF-Map-Unfold"
   Target_en_us "Unfold Map"
   Modified 1730472344
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9BC}" {
   Id "ABF_101_Company_A"
   Target_en_us "Able"
   Target_de_de "Able"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9C9}" {
   Id "ABF_101_Company_B"
   Target_en_us "Bravo"
   Target_de_de "Bravo"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9D4}" {
   Id "ABF_101_Company_C"
   Target_en_us "Charlie"
   Target_de_de "Charlie"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9E3}" {
   Id "ABF_101_Company_D"
   Target_en_us "Delta"
   Target_de_de "Delta"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9E8}" {
   Id "ABF_101_Company_E"
   Target_en_us "Echo"
   Target_de_de "Echo"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9F7}" {
   Id "ABF_101_Company_F"
   Target_en_us "Foxtrot"
   Target_de_de "Foxtrot"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9FD}" {
   Id "ABF_101_Company_G"
   Target_en_us "Golf"
   Target_de_de "Golf"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1EA05}" {
   Id "ABF_101_Company_H"
   Target_en_us "Hotel"
   Target_de_de "Hotel"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1EA13}" {
   Id "ABF_101_Platoon_1"
   Target_en_us "1"
   Target_de_de "1"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1EA1B}" {
   Id "ABF_101_Platoon_2"
   Target_en_us "2"
   Target_de_de "2"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1EA20}" {
   Id "ABF_101_Platoon_3"
   Target_en_us "3"
   Target_de_de "3"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1EA29}" {
   Id "ABF_101_Platoon_4"
   Target_en_us "Mortar Section"
   Target_de_de "Mortar Section"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1EA34}" {
   Id "ABF_101_Platoon_5"
   Target_en_us "Fire Support Team"
   Target_de_de "Fire Support Team"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6716D76CFB103495}" {
   Id "ABF_Carry_Rotate"
   Target_en_us "Rotate"
   Target_de_de "Drehen"
   Modified 1729564232
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{657EB8B819A75AC8}" {
   Id "ABU-Group-Fireteam-MED"
   Target_en_us "Fire Team with Medic"
   Target_de_de "Fire Team with Medic"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{657EB8B9CF40B861}" {
   Id "ABU-Group-Fireteam-RM"
   Target_en_us "Fire Team with Rifleman"
   Target_de_de "Fire Team with Rifleman"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{657EB8B9649F69AA}" {
   Id "ABU-Group-RifleSquad"
   Target_en_us "Rifle Squad"
   Target_de_de "Rifle Squad"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65FD0BB8FB1500CB}" {
   Id "ABU-Item_Saline_Big_Name"
   Target_en_us "Saline Solution - Big Bag"
   Target_de_de "Kochsalzlösung – großer Rucksack"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E98A}" {
   Id "ABU-Role_AutomaticRifleman"
   Target_en_us "Automatic Rifleman"
   Target_de_de "Automatic Rifleman"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65BAB95BEF2720BC}" {
   Id "ABU-Role_DMR"
   Target_en_us "Designated Marksman"
   Target_de_de "Designated Marksman"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E990}" {
   Id "ABU-Role_Grenadier"
   Target_en_us "Grenadier"
   Target_de_de "Grenadier"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{6562EDB4C8CD2966}" {
   Id "ABU-Role_Medic"
   Target_en_us "Medic"
   Target_de_de "Medic"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E99D}" {
   Id "ABU-Role_Rifleman"
   Target_en_us "Rifleman"
   Target_de_de "Rifleman"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{669265AF6104DB29}" {
   Id "ABU-Role_RTO"
   Target_en_us "Radio Telephone Operator"
   Target_de_de "Radio Telephone Operator"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9A8}" {
   Id "ABU-Role_SquadLeader"
   Target_en_us "Squad Leader"
   Target_de_de "Squad Leader"
   ActorGender NONE
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{651AF1B448E1E9B6}" {
   Id "ABU-Role_TeamLeader"
   Target_en_us "Team Leader"
   Target_de_de "Team Leader"
   NonTranslatable 1
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65952E705B66804B}" {
   Id "ABU-Role_WS_AG"
   Target_en_us "Assistant Gunner"
   Target_de_de "Assistant Gunner"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65952E703A6EEE59}" {
   Id "ABU-Role_WS_AH"
   Target_en_us "Ammo Handler"
   Target_de_de "Ammo Handler"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65952E701E4E3036}" {
   Id "ABU-Role_WS_AT"
   Target_en_us "Anti Tank"
   Target_de_de "Anti Tank"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
  CustomStringTableItem "{65952E73E08F746C}" {
   Id "ABU-Role_WS_MG"
   Target_en_us "Machine Gunner"
   Target_de_de "Machine Gunner"
   Modified 1729311049
   Author "Faldi"
   LastChanged "Faldi"
  }
 }
}