StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6927131CB2819266}" {
   Id "SUI-Settings-SpeedUI-EnableBar"
   Target_en_us "Show Progress Bar"
   Target_de_de "Fortschrittsbalken anzeigen"
   Modified 1764169531
   Author "Sky"
   LastChanged "Sky"
  }
  CustomStringTableItem "{6927131CADA498FE}" {
   Id "SUI-Settings-SpeedUI-EnableUnits"
   Target_en_us "Show Units"
   Target_de_de "Einheiten anzeigen"
   Modified 1764169520
   Author "Sky"
   LastChanged "Sky"
  }
  CustomStringTableItem "{6927131C3B5CB272}" {
   Id "SUI-Settings-SpeedUI-Main"
   Target_en_us "General Speedometer Settings"
   Target_de_de "Allgemeine Tacho-Einstellungen"
   Modified 1764169196
   Author "Sky"
   LastChanged "Sky"
  }
  CustomStringTableItem "{6927131DCE666F76}" {
   Id "SUI-Settings-SpeedUI-Player"
   Target_en_us "Player Speedometer"
   Target_de_de "Spieler Tacho"
   Modified 1764168985
   Author "Sky"
   LastChanged "Sky"
  }
  CustomStringTableItem "{6927131F065BEDBE}" {
   Id "SUI-Settings-SpeedUI-Transparency"
   Target_en_us "HUD Transparency"
   Target_de_de "HUD-Transparenz"
   Modified 1764169612
   Author "Sky"
   LastChanged "Sky"
  }
  CustomStringTableItem "{6927131F6C14C86F}" {
   Id "SUI-Settings-SpeedUI-Units"
   Target_en_us "Measurement Units"
   Target_de_de "Maßeinheiten"
   Modified 1764169466
   Author "Sky"
   LastChanged "Sky"
  }
  CustomStringTableItem "{6927131CE2A17FEE}" {
   Id "SUI-Settings-SpeedUI-Vehicle"
   Target_en_us "Vehicle Speedometer"
   Target_de_de "Fahrzeug Tacho"
   Modified 1764169260
   Author "Sky"
   LastChanged "Sky"
  }
 }
}