ActionManager {
 Actions {
  Action SpeedHUDToggle {
   InputSource InputSourceCombo "{68D3555C2E865D8C}" {
    FilterPreset "select"
    Sources {
     InputSourceValue "{68D3555C1CFDAF58}" {
      FilterPreset "select"
      Input "keyboard:KC_5"
     }
     InputSourceValue "{68D3555C1E72D10A}" {
      FilterPreset "select"
      Input "keyboard:KC_LCONTROL"
     }
    }
   }
  }
 }
 Contexts {
  ActionContext SpeedUI {
   Priority 100
   Flags 0x2 0
   ActionRefs {
    "SpeedHUDToggle"
   }
  }
 }
}