SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{68D3555C97BE6424}" {
   m_sName "SpeedUI"
   m_sDisplayName "SpeedUI"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{68D3555C985551BE}" {
     m_sActionName "SpeedHUDToggle"
     m_sDisplayName "SpeedHUDToggle"
     m_sPreset "select"
    }
   }
  }
 }
}